linters-settings:
  custom:
    aslint:
      path: aslint.so
  funlen:
    # Default: 60
    lines: 100
    # Default: 40
    statements: 65
  # cyclop:
  #   # Default: 10
  #   max-complexity: 20
  nestif:
    # Default: 5
    min-complexity: 10
  godot:
    capital: true

linters:
  enable:
    - aslint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - containedctx
    # - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - forcetypeassert
    # - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    # - gocognit
    - goconst
    - gocritic
    - godot
    - gofmt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace

issues:
  exclude-rules:
    - linters:
        - gocritic
      # This complains about CGO
      text: "underef: could simplify"